### ISSUE TITLE
Cisco ScreenPop opens a popup also when a call ends

### ISSUE THREAD

**Issue by floatingpurr** [CiscoDevNet/finesse-sample-code#12]
I'm using the default `screenPop.js` but instead of opening an iframe I want to open a custom url in a new tab based on call variables with: `window.open(myUrl);`

All works fine, however sometimes when the agent presses the end button, another identical popup is triggered. I logged the `user.getState()` and, in those cases, the user is still in the `Talking` state unless she has already pressed the end button.

 Is there a way to fix this?

**Comment by dekwan** [comment]
Hi,

Will reply in the Cisco DevNet forum here: https://community.cisco.com/t5/contact-center/cisco-screepop-opens-a-popup-also-when-a-call-ends/m-p/4046702#M10815

Thanx,
Denise

**Comment by floatingpurr** [comment]
Oh thanks. I'm sorry for the double posting, but I did not know which was the best place to ask for support. Looking forward to hearing from you there, then.
