### ISSUE TITLE
SleekXMPP deprecated

### ISSUE THREAD

**Issue by IllicitMoonshine** [CiscoDevNet/finesse-sample-code#16]
Any chance of an updated example code using either Slixmpp which replaced SleekXMPP or another XMPP library?  If there is no plans for that it is fine I just managed to stumble here from the [Cisco Site](https://developer.cisco.com/docs/finesse/#!sample-gadgets/sample-gadgets).

**Comment by dekwan** [comment]
The non gadget sample has already been updated to use strophe and websocket instead. This is the recommended way to go: https://github.com/CiscoDevNet/finesse-sample-code/tree/master/NonGadgetSampleWithStropheAndWebsocket

**Comment by IllicitMoonshine** [comment]
I apologize for not catching that!  Thank you so much!
