### ISSUE TITLE
Typing text box shrinks after posting #Important message

### ISSUE THREAD

**Issue by theschwartz42** [CiscoDevNet/finesse-sample-code#2]
Seeing a minor issue that only occurs after you send an Important message where the text box shrinks to a small width.  The only fix seems to be to reload the page, tab changes don't help.
<img width="859" alt="screen shot 2016-10-01 at 1 28 28 am" src="https://cloud.githubusercontent.com/assets/6934649/19012025/65567106-8776-11e6-9318-6918b09fc342.png">

**Comment by dekwan** [comment]
Hm. I must not have merged the code changes correctly before posting. In _postData, change
$('#msg').removeClass(className);
to 
$('#msg').removeClass("myinputimp"); 

Thanks for the catch. Will fix v1.1.

**Comment by theschwartz42** [comment]
That fixed it, thanks again
