### ISSUE TITLE
EmbeddedWebApp Gadget only shows gray background 

### ISSUE THREAD

**Issue by T2Bowen** [CiscoDevNet/finesse-sample-code#3]
I have installed EmbeddedWebApp gadget on several UCCX-11.x-systems where it has been working fine. 
But now when i install this gadget on a UCCX 10.6-system i don´t get any website to load.
The Gadget only shows a gray background.
![bild](https://cloud.githubusercontent.com/assets/21955314/21176122/a6eb03bc-c1e5-11e6-83bd-9a2bba9c2fdb.png)

This has happened before also on the other UCCX-systems, but suddenly started to work. 
I am using the Cisco.com website at this moment since i know this can be loaded in an iFrame.
(customer site also works in a iFrame)

    gadgets.HubSettings.onConnect = function () {
                    finesse.modules.EmbeddedWebAppGadget.init("https://www.cisco.com");

[Edit] After downloading the 10.6-version and installing a Firefox-Addon to Enable MixedContent i got it working.

But the issue is still why the gadget works on other system in version 11.x. with both mixed content and using https-sites inside an iFrame without installing a Firefox-Addon.

**Comment by dekwan** [comment]
Correct. You need to match the version of the Finesse system with the gadget version.

It is a browser restriction of mixed mode and not the gadget itself. See this Mozilla article: https://support.mozilla.org/en-US/kb/mixed-content-blocking-firefox
